from dictionary import *
import linkedlist
dict = dictionary(5)

print("-_-_-_-_-_- Prueba insert -_-_-_-_-_-")
insert(dict, 25, 25)
print(dict[0].head.value)
insert(dict, 3, 3)
print(dict[3].head.value)
insert(dict, 4, 4)
print(dict[4].head.value)
insert(dict, 1, 1)
print(dict[1].head.value)
insert(dict, 2, 2)
print(dict[2].head.value)
insert(dict, 6, 6)
insert(dict, 11, 11)
linkedlist.printlist(dict[1])

print(" ")
print("-_-_-_-_-_- Prueba delete -_-_-_-_-_-")
linkedlist.printlist(dict[1])
delete(dict, 11)
print("Borro 11")
linkedlist.printlist(dict[1])
insert(dict, 11, 11)
delete(dict, 1)
print("Borro 1")
linkedlist.printlist(dict[1])
insert(dict, 1, 1)
delete(dict, 11)
print("Borro 11")
linkedlist.printlist(dict[1])
insert(dict, 11, 11)
insert(dict, 16, 16)
insert(dict, 21, 21)
print("Inserto varios con con k = 1")
linkedlist.printlist(dict[1])
print("Borro el ultimo")
delete(dict, 6)
linkedlist.printlist(dict[1])
print("Voy a un k que tenga solo un elemento, k = 2")
linkedlist.printlist(dict[2])
print("Borro key 2")
delete(dict, 2)
print(dict[2])

print(" ")
print("-_-_-_-_-_- Prueba search -_-_-_-_-_-")
print(search(dict, 1))
print(search(dict, 100))
print(search(dict, 87))
print(search(dict, 25))
print(search(dict, 3))
print(search(dict, 7))