import pm
print(pm.existChar("hola", "c"))
print(pm.isPalindrome("hooh"))
print(pm.getBiggestIslandLen("hhhhhhoola2222dd"))
print(pm.isAnagram("holaaas", "aaasloh"))
print(pm.isAnagram("holaaas", "aaasldh"))
print(pm.verifyBalancedParentheses("())()()()()"))
print(pm.verifyBalancedParentheses("()()()()()"))
print(pm.verifyBalancedParentheses(")()()()()()"))
print(pm.verifyBalancedParentheses("(()()()()())"))
print(pm.reduceLen("aabcddefffffg"))
print(pm.reduceLen("aaaaaaaaaaaa"))
print(pm.reduceLen("aaaaaaaaaaa"))
print(pm.reduceLen("aadaaeaafaadaaaaa"))
print(pm.isContained("asslrdcrveldsajsac", "arveja"))
print(pm.isContained("asslrdcrveldsajsc", "arveja"))
print(pm.isContained("asslrdcrveldsajsca", "arveja"))
print(pm.isContained("aarvejasslrdcrveldsajsca", "arveja"))